export const zhCN = {
  brand: "BeatPrints",
  tagline: "把喜欢的音乐，排成一张海报",
  heroTitle: "让一首歌，\n留下纸面的形状。",
  heroBody:
    "从真实音乐目录中找到准确版本，挑选四行歌词，生成一张可以下载收藏的 PNG 海报。",
  track: "单曲海报",
  album: "专辑海报",
  searchTrack: "搜索歌曲、歌手或专辑",
  searchAlbum: "搜索专辑或歌手",
  search: "搜索",
  searching: "正在查找",
  source: "搜索来源",
  allSources: "全部来源",
  selectWork: "选择作品",
  selectedWork: "已选作品",
  lyrics: "选择四行歌词",
  lyricsHelp: "默认选中前四行，也可以从整首歌词中任选四行。",
  manualLyrics: "手动填写",
  catalogLyrics: "从歌词中选择",
  platform: "添加平台入口",
  appearance: "确定海报外观",
  generate: "生成海报",
  generating: "正在生成海报",
  download: "下载 PNG",
  regenerate: "调整并重新生成",
  startOver: "换一个作品",
} as const

export type Messages = typeof zhCN
